# Generated by Django 6.0.3 on 2026-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dere_image',
            field=models.ImageField(blank=True, null=True, upload_to='dare_images/'),
        ),
    ]
