# Generated by Django 6.0.3 on 2026-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_dere_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Hindi', 'Hindi'), ('Science', 'Science'), ('Maths', 'Maths')], max_length=15)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='emai',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dere_image',
        ),
    ]
