# Generated by Django 6.0.2 on 2026-03-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_attendance_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emai',
            new_name='email',
        ),
    ]
